platform :ios, '9.0'
use_frameworks!

target "NguyenKimApp" do
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'GoogleSignIn'
    pod 'RNGoogleSignIn'    
    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end

